language: csharp
solution: ./Alamut.AspNet.sln
dist: bionic
mono: none
dotnet: 2.2.300
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test
deploy:
  provider: script
  script:
    - dotnet pack ./src/Alamut.AspNet/Alamut.AspNet.csproj --output ../../ --include-source  
    - dotnet nuget push *.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    branch: release